<?php return array (
  "errorState" => 
  array (
    "noError" => __("No error", __FILE__),
    "abnormalCommunication" => __("Problème de connexion", __FILE__),
    "boilerDisconnection" => __("Cafetière électrique déconnectée", __FILE__),
    "ntcAbnormality" => __("Vérifier le capteur de température", __FILE__),
    "transmissionSystemAbnormality" => __("Problème de signal", __FILE__),
    "grindingSystemAbnormality" => __("Vérifier le système de broyage", __FILE__),
    "pipelineBlockage" => __("Tuyau bloqué", __FILE__),
    "coffeeBeansRunOut" => __("En rupture de café", __FILE__),
    "temperatureIsTooLow" => __("La température est trop basse", __FILE__),
    "temperatureIsTooHigh" => __("La température est trop élevée", __FILE__),
    "waterTankShortOfWater" => __("Manque d\"eau dans le réservoir", __FILE__),
    "valveFaulty" => __("Vérifier la vanne", __FILE__),
    "brewingDoorOpen" => __("Trappe de l\"unité de chauffage ouverte", __FILE__),
    "wasteWaterTrayError" => __("Vérifier le bac à eau", __FILE__),
    "wasteWaterTrayFull" => __("Bac à eau plein", __FILE__),
    "coffeeGroundsTankError" => __("Vérifier le récipient à marc de café", __FILE__),
    "coffeeGroundsTankFull" => __("Récipient à marc de café plein", __FILE__),
    "coffeeSpoutCoverError" => __("Vérifier le couvercle du bec de la cafetière", __FILE__),
    "brewingUnitError" => __("Vérifier l\"unité de chauffage", __FILE__),
    "brewingBoilerError" => __("Vérifier la chaudière", __FILE__),
  ),
  "petActivity" => 
  array (
    "toileting" => __("Toileting", __FILE__),
  ),
  "plantType" => 
  array (
    "none" => __("Aucun(e)", __FILE__),
    "lettuce_caesarsGreen" => __("Laitue verte César", __FILE__),
    "lettuce_jeokOak" => __("Laitue rouge coréenne", __FILE__),
    "tatsoi_vitamin" => __("Tatsoi", __FILE__),
    "collardLeafKale" => __("Feuilles de chou vert", __FILE__),
    "leafRedChicory" => __("Chicorée à feuilles rouges", __FILE__),
    "garlandChrysanthemum" => __("Chrysanthème de guirlande", __FILE__),
    "pakchoi" => __("Bok choy", __FILE__),
    "leafMustard" => __("Moutarde brune", __FILE__),
    "basil" => __("Basilic", __FILE__),
    "rucola" => __("Roquette", __FILE__),
    "cilantro" => __("Coriandre", __FILE__),
    "dill" => __("Aneth", __FILE__),
    "thyme" => __("Thym", __FILE__),
    "lemonBalm" => __("Mélisse", __FILE__),
    "catnip" => __("Cataire", __FILE__),
    "endive" => __("Endive", __FILE__),
    "lettuce_multiGreen" => __("Laitue multifeuille", __FILE__),
    "napaCabbage" => __("Chou chinois", __FILE__),
    "appleMint" => __("Menthe à feuilles rondes", __FILE__),
    "thaiBasil" => __("Basilic thaï", __FILE__),
    "peppermint" => __("Menthe poivrée", __FILE__),
    "burningBushSpindletree" => __("Buisson ardent", __FILE__),
    "lolloBionda_Bartimer" => __("Laitue lollo verte", __FILE__),
    "lettuce_miniRomaine" => __("Mini laitue romaine", __FILE__),
    "newGreen" => __("Jeunes pousses", __FILE__),
    "redVeinedSorrel" => __("Oseille à veines rouges", __FILE__),
    "sage" => __("Sauge", __FILE__),
    "eggplant" => __("Aubergine", __FILE__),
    "pepper" => __("Poivre", __FILE__),
    "strawberry" => __("Fraise", __FILE__),
    "rosemary" => __("Romarin", __FILE__),
    "monstera" => __("Monstera", __FILE__),
    "mint" => __("Menthe", __FILE__),
    "cherryTomato" => __("Tomate cerise", __FILE__),
    "garlicChives" => __("Ciboule", __FILE__),
    "sansevieria" => __("Langue de belle-mère", __FILE__),
    "lettuce" => __("Laitue", __FILE__),
    "peaceLily" => __("Lys de la paix", __FILE__),
    "parsley" => __("Persil", __FILE__),
    "paprika" => __("Paprika", __FILE__),
    "peperomia" => __("Pépéromie", __FILE__),
    "philodendron" => __("Philodendron", __FILE__),
    "UNKNOWN" => __("Inconnu", __FILE__),
  ),
  "operatingState" => 
  array (
    "emptyStation" => __("emptyStation", __FILE__),
    "internalWash" => __("internalWash", __FILE__),
    "cleaningStart" => __("cleaningStart", __FILE__),
    "cleaningEnd" => __("cleaningEnd", __FILE__),
  ),
  "chargingDetail" => 
  array (
    "noCharging" => __("Pas en charge", __FILE__),
    "veryFastCharging" => __("Charge très rapide", __FILE__),
    "fastCharging" => __("Charge rapide", __FILE__),
    "v2lDischarge" => __("Décharge V2L", __FILE__),
    "v2lCharging" => __("Charge V2L", __FILE__),
    "v2lStop" => __("V2L arrêté", __FILE__),
    "v2xDischarge" => __("Décharge V2X", __FILE__),
    "v2xCharging" => __("Charge V2X", __FILE__),
    "reseveredCharging" => __("Charge planifiée", __FILE__),
  ),
  "frontLeftDoor" => 
  array (
    "open" => __("Ouvert", __FILE__),
    "closed" => __("Fermé", __FILE__),
    "locked" => __("Verrouillé", __FILE__),
  ),
  "rearRightDoor" => 
  array (
    "open" => __("Ouvert", __FILE__),
    "closed" => __("Fermé", __FILE__),
    "locked" => __("Verrouillé", __FILE__),
  ),
  "rearLeftDoor" => 
  array (
    "open" => __("Ouvert", __FILE__),
    "closed" => __("Fermé", __FILE__),
    "locked" => __("Verrouillé", __FILE__),
  ),
  "lockState" => 
  array (
    "unknown" => __("Inconnu", __FILE__),
  ),
  "frontRightDoor" => 
  array (
    "open" => __("Ouvert", __FILE__),
    "closed" => __("Fermé", __FILE__),
    "locked" => __("Verrouillé", __FILE__),
  ),
);
