name: "Check php translations of cmdName and enums"

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout files"
        uses: actions/checkout@v3

      - name: "Install PHP"
        run: sudo apt-get install php libapache2-mod-php php-cli

      - name: "Launch check"
        run: |
          php check_capabilities_and_translations.php
          echo "ENUMS_VAR<<EOF" >> $GITHUB_ENV
          cat enums.php >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "CMDNAME_VAR<<EOF" >> $GITHUB_ENV
          cat cmdName.php >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            enums.php
            cmdName.php
          branch: translations_${{ env.GITHUB_RUN_ID }}
          delete-branch: true
          title: "Missing cmdname or enums"
          body: |
            ## $this->enums
            ```
            ${{ env.ENUMS_VAR }}
            ```
            ## $this->cmdName
            ```
            ${{ env.CMDNAME_VAR }}
            ```
          commit-message: "Auto check cmdname and enums of php file"
