name: "Generate capabilities"
on:
  workflow_dispatch:
  schedule:
    - cron: '13 05 */7 * *'

jobs:
  build:
    name: "Generate capabilities, presentation and translations"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v3

      - name: "Setup smartthings-cli"
        run: |
          wget "https://github.com/SmartThingsCommunity/smartthings-cli/releases/download/%40smartthings%2Fcli%401.8.2/smartthings-linux-x64.tar.gz"
          tar -xvf smartthings-linux-x64.tar.gz

      - name: "Use first secret"
        run: |
          SMARTTHINGS_TOKEN=$(echo ${{ secrets.SMARTTHINGS_TOKENS }} | head -n 1)
          echo "SMARTTHINGS_TOKEN=$SMARTTHINGS_TOKEN" >> $GITHUB_ENV

      - name: "Download smartthings capabilities"
        run: ./smartthings capabilities -s -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o capabilities.json

      - name: "Process capabilities"
        run: |
          mkdir -p json
          count=0
          process_capability() {
            local id=$1
            local version=$2
            echo "Processing $id version $version"
            ./smartthings capabilities $id -s -j --token ${{ env.SMARTTHINGS_TOKEN }} -o json/$id.json || true
            ./smartthings capabilities:presentation $id $version -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/${id}Presentation.json || true
            ./smartthings capabilities:translations $id $version fr -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/$id.i18n.fr.json || true
            ./smartthings capabilities:translations $id $version en -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/$id.i18n.en.json || true
          }
          cat capabilities.json | jq -c '.[]' | while read capability; do
            if [ $count -ge 30 ]; then
              break
            fi
            id=$(echo $capability | jq -r '.id')
            version=$(echo $capability | jq -r '.version')
            process_capability $id $version
            count=$((count+1))
          done
          cat extra_capabilities_fix.json | jq -c '.[]' | while read capa; do
            if [ $count -ge 30 ]; then
              break
            fi
            id=$(echo $capa | jq -r '.id')
            version=$(echo $capa | jq -r '.version')
            process_capability $id $version
            count=$((count+1))
          done

      - name: "Print README.md"
        run: |
          PRINT="## SmartThings Capabilities\n"
          PRINT+="#### Last Update: "$(date -I)"\n"
          PRINT+="#### Edited by Flobul for Jeedom solution\n\n"
          PRINT+="* [SmartThings Reference](https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html)\n"
          PRINT+="* [SmartThings API](https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#tag/capabilities)\n"
          PRINT+="* [SmartThings CLI](https://github.com/SmartThingsCommunity/smartthings-cli)\n"
          PRINT+="* [Create Personal Access Token](https://account.smartthings.com/tokens)\n"
          PRINT+="* [Plugin Documentation](https://flobul-domotique.fr/documentation-du-plugin-smartthings-pour-jeedom/)\n"
          PRINT+="* [Plugin Jeedom Market](https://market.jeedom.com/index.php?v=d&p=market_display&id=4099)\n"
          PRINT+="| Capability | Version | Status | Capability Presentation | Translation i18n\n"
          PRINT+="| ---- | ---- | ---- | ---- | ---- |\n\n"
          ls json/*.json | grep -v i18n | grep -v Presentation.json | while read file; do
            json=$(cat $file | sed 's/\\//g')
            name=$(echo "$json" | jq -r '.name') || true
            id=$(echo "$json" | jq -r '.id') || true
            statuses=$(echo "$json" | jq -r '.status') || true
            versions=$(echo "$json" | jq -r '.version') || true
            presentation=""
            i18n=""
            if [ -f json/${id}Presentation.json ]; then
              presentation="[json](./json/${id}Presentation.json)"
            fi
            if [ -f json/${id}.i18n.fr.json ]; then
              i18n="[json](./json/${id}.i18n.fr.json)"
            fi
            PRINT+="| [$name](./json/$id.json) | $versions | $statuses | $presentation | $i18n |\n"
          done
          echo $PRINT > README.md

      - name: "Set up git config"
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "flobul.jeedom@gmail.com"

      - name: "Create Pull Request for each modified file"
        run: |
          git fetch origin
          git checkout master
          git pull origin master

          create_pr() {
            local file=$1
            branch_name="update-$(basename $file)"
            git checkout -b $branch_name
            git add $file
            git commit -m "Update $file"
            diff=$(git diff HEAD~1 -- $file)
            if git ls-remote --heads origin $branch_name | grep -q $branch_name; then
              git push origin $branch_name --force
            else
              git push origin $branch_name
            fi
            if ! gh pr view --json headRefName -q .headRefName | grep -q $branch_name; then
              gh pr create --title "Update $file" --body "Automated update for $file\n\n```diff\n$diff\n```" --base master --head $branch_name
            else
              pr_url=$(gh pr view --json url -q .url | grep $branch_name)
              gh pr edit $pr_url --body "Automated update for $file\n\n```diff\n$diff\n```"
            fi
            git checkout master
            git branch -D $branch_name
          }

          create_combined_pr() {
            local branch_name="update-combined"
            git checkout -b $branch_name
            git add json/*.i18n.fr.json json/*.i18n.en.json json/*Presentation.json
            git commit -m "Update combined files"
            diff=$(git diff HEAD~1 -- json/*.i18n.fr.json json/*.i18n.en.json json/*Presentation.json)
            if git ls-remote --heads origin $branch_name | grep -q $branch_name; then
              git push origin $branch_name --force
            else
              git push origin $branch_name
            fi
            if ! gh pr view --json headRefName -q .headRefName | grep -q $branch_name; then
              gh pr create --title "Update combined files" --body "Automated update for combined files\n\n```diff\n$diff\n```" --base master --head $branch_name
            else
              pr_url=$(gh pr view --json url -q .url | grep $branch_name)
              gh pr edit $pr_url --body "Automated update for combined files\n\n```diff\n$diff\n```"
            fi
            git checkout master
            git branch -D $branch_name
          }

          for file in json/*.json; do
            if [[ $file == *.i18n.fr.json || $file == *.i18n.en.json || $file == *Presentation.json ]]; then
              continue
            fi
            if git diff --quiet HEAD -- $file; then
              echo "No changes in $file"
            else
              create_pr $file
            fi
          done

          # Create a combined PR for the excluded files
          if git diff --quiet HEAD -- json/*.i18n.fr.json json/*.i18n.en.json json/*Presentation.json; then
            echo "No changes in combined files"
          else
            create_combined_pr
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
