name: "Generate capabilities"

on:
  workflow_dispatch
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout files"
        uses: actions/checkout@v3

      - name: "Setup php"
        run: sudo apt-get install php libapache2-mod-php php-cli

      - name: "Setup smartthings-cli"
        run: |
          wget "https://github.com/SmartThingsCommunity/smartthings-cli/releases/download/%40smartthings%2Fcli%401.8.2/smartthings-linux-x64.tar.gz"
          tar -xvf smartthings-linux-x64.tar.gz
          ./smartthings --help
      - name: "Use first secret"
        run: |
          SMARTTHINGS_TOKEN=$(echo ${{ secrets.SMARTTHINGS_TOKENS }} | head -n 1)
          echo "SMARTTHINGS_TOKEN=$SMARTTHINGS_TOKEN" >> $GITHUB_ENV

      - name: "List smartthings capabilities"
        run: |
          ./smartthings capabilities -s -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o capabilities.json
          CAPABILITIES=$(cat capabilities.json)
          echo "CAPABILITIES=${{ env.CAPABILITIES }}" >> $GITHUB_ENV

      - name: "Process each capability"
        run: |
          mkdir -p json
          echo '${{ env.CAPABILITIES }}' | jq -c '.[]' | while read capability; do
            id=$(echo $capability | jq -r '.id')
            version=$(echo $capability | jq -r '.version')
            echo "Processing ID: $id"

            # Ici tu peux exécuter ta commande bash avec l'id
            # Remplace 'echo' par ta commande réelle
            ./smartthings capabilities $id -s -j --token ${{ env.SMARTTHINGS_TOKEN }} > json/$id.json
            ./smartthings capabilities:translations $id $version fr -j --token ${{ env.SMARTTHINGS_TOKEN }} -o json/$id.i18n.fr.json
            ./smartthings capabilities:translations $id $version en -j --token ${{ env.SMARTTHINGS_TOKEN }} -o json/$id.i18n.en.json
          done

      - name: "List json directory"
        run: ls -lh json/

      - name: "Create Pull Request to plugin..."
        uses: peter-evans/create-pull-request@v6
        with:
          path: 'json'
          branch: translations
          delete-branch: true
          title: "Update capabilities"
          body: "Automated capabilities update"
          commit-message: "Auto update capabilities"
