name: "Generate capabilities"
on:
  workflow_dispatch:
  schedule:
    - cron: '13 05 */7 * *'

jobs:
  build:
    name: "Generate capabilities, presentation, and translations"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v3

      - name: "Setup smartthings-cli"
        run: |
          wget "https://github.com/SmartThingsCommunity/smartthings-cli/releases/download/%40smartthings%2Fcli%401.8.2/smartthings-linux-x64.tar.gz"
          tar -xvf smartthings-linux-x64.tar.gz

      - name: "Set up environment variables"
        run: |
          SMARTTHINGS_TOKEN=$(echo ${{ secrets.SMARTTHINGS_TOKENS }} | head -n 1)
          echo "SMARTTHINGS_TOKEN=$SMARTTHINGS_TOKEN" >> $GITHUB_ENV

      - name: "Download smartthings capabilities"
        run: ./smartthings capabilities -s -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o capabilities.json

      - name: "Process capabilities"
        run: |
          mkdir -p json
          count=0

          process_capability() {
            local id=$1
            local version=$2
            echo "Processing $id version $version"
            ./smartthings capabilities $id -s -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/$id.json || true
            ./smartthings capabilities:presentation $id $version -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/${id}Presentation.json || true
            ./smartthings capabilities:translations $id $version fr -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/$id.i18n.fr.json || true
            ./smartthings capabilities:translations $id $version en -j --token "${{ env.SMARTTHINGS_TOKEN }}" -o json/$id.i18n.en.json || true
          }

          jq -c '.[]' capabilities.json | while read capability; do
            id=$(echo $capability | jq -r '.id')
            version=$(echo $capability | jq -r '.version')
            process_capability $id $version
            count=$((count+1))
          done

          if [ -f extra_capabilities_fix.json ]; then
            jq -c '.[]' extra_capabilities_fix.json | while read capa; do
              id=$(echo $capa | jq -r '.id')
              version=$(echo $capa | jq -r '.version')
              process_capability $id $version
              count=$((count+1))
            done
          fi

      - name: "Generate README.md"
        run: |
          PRINT="## SmartThings Capabilities\n"
          PRINT+="#### Last Update: "$(date -I)"\n"
          PRINT+="#### Edited by Flobul for Jeedom solution\n\n"
          PRINT+="* [SmartThings Reference](https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html)\n"
          PRINT+="* [SmartThings API](https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#tag/capabilities)\n"
          PRINT+="* [SmartThings CLI](https://github.com/SmartThingsCommunity/smartthings-cli)\n"
          PRINT+="* [Create Personal Access Token](https://account.smartthings.com/tokens)\n"
          PRINT+="* [Plugin Documentation](https://flobul-domotique.fr/documentation-du-plugin-smartthings-pour-jeedom/)\n"
          PRINT+="* [Plugin Jeedom Market](https://market.jeedom.com/index.php?v=d&p=market_display&id=4099)\n"
          PRINT+="| Capability | Version | Status | Capability Presentation | Translation i18n |\n"
          PRINT+="| ---- | ---- | ---- | ---- | ---- |\n\n"

          for file in json/*.json; do
            if [[ $file == *i18n* || $file == *Presentation.json ]]; then
              continue
            fi

            json=$(cat "$file" | sed 's/\\//g')
            name=$(echo "$json" | jq -r '.name')
            id=$(echo "$json" | jq -r '.id')
            statuses=$(echo "$json" | jq -r '.status')
            versions=$(echo "$json" | jq -r '.version')

            presentation=""
            i18n=""
            [ -f "json/${id}Presentation.json" ] && presentation="[json](./json/${id}Presentation.json)"
            [ -f "json/${id}.i18n.fr.json" ] && i18n="[json](./json/${id}.i18n.fr.json)"

            PRINT+="| [$name](./json/$id.json) | $versions | $statuses | $presentation | $i18n |\n"
          done

          echo -e "$PRINT" > README.md

      - name: "Set up git config"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "flobul.jeedom@gmail.com"
          
      - name: "Create Pull Requests"
        run: |
          git fetch origin
          git checkout master
      
          # Vérifier les modifications
          git status
          git diff
      
          create_pr() {
            local file=$1
            local branch_name="update-$(basename "$file")"
            echo "Creating PR for $file on branch $branch_name"
      
            # Nettoyage des branches existantes
            git branch -D "$branch_name" || true
            git push origin --delete "$branch_name" || true
      
            # Création de la branche et commit
            git checkout -b "$branch_name"
            git add "$file"
            git commit -m "Update $file"
            git push origin "$branch_name"
      
            # Création ou mise à jour de la PR
            if ! gh pr view --json headRefName -q .headRefName | grep -q "$branch_name"; then
              gh pr create --title "Update $file" --body "Automated update for $file" --base master --head "$branch_name" --verbose
            else
              pr_url=$(gh pr view --json url -q .url)
              gh pr edit "$pr_url" --body "Automated update for $file" --verbose
            fi
      
            git checkout master
            git branch -D "$branch_name"
          }
      
          # Traiter chaque fichier JSON individuellement
          for file in json/*.json; do
            if [[ $file == *.i18n.fr.json || $file == *.i18n.en.json || $file == *Presentation.json ]]; then
              continue
            fi
            if ! git diff --quiet HEAD -- "$file"; then
              create_pr "$file"
            fi
          done
      
          # PR groupée pour les traductions et présentations
          if ! git diff --quiet HEAD -- json/*.i18n.*.json json/*Presentation.json; then
            git branch -D "update-translations-and-presentations" || true
            git push origin --delete "update-translations-and-presentations" || true
      
            git checkout -b "update-translations-and-presentations"
            git add json/*.i18n.*.json json/*Presentation.json
            git commit -m "Update translations and presentations"
            git push origin "update-translations-and-presentations"
            gh pr create --title "Update translations and presentations" --body "Automated update for translation and presentation files." --base master --head "update-translations-and-presentations" --verbose
          fi
      
          # PR pour README.md
          if ! git diff --quiet HEAD -- README.md; then
            git branch -D "update-readme" || true
            git push origin --delete "update-readme" || true
      
            git checkout -b "update-readme"
            git add README.md
            git commit -m "Update README.md"
            git push origin "update-readme"
            gh pr create --title "Update README.md" --body "Automated update for README.md" --base master --head "update-readme" --verbose
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
